In [1]:
import numpy as np

#### Задание 5.1

$E = \begin{bmatrix}
       1 & 0 & 0 & 0 & 0 \\
       0 & 1 & 0 & 0 & 0 \\
       0 & 0 & 1 & 0 & 0 \\
       0 & 0 & 0 & 1 & 0 \\
       0 & 0 & 0 & 0 & 1 
       \end{bmatrix} * 5 = \begin{bmatrix}
       5 & 0 & 0 & 0 & 0 \\
       0 & 5 & 0 & 0 & 0 \\
       0 & 0 & 5 & 0 & 0 \\
       0 & 0 & 0 & 5 & 0 \\
       0 & 0 & 0 & 0 & 5
     \end{bmatrix} - 1 = \begin{bmatrix}
       4 & 0 & 0 & 0 & 0 \\
       0 & 4 & 0 & 0 & 0 \\
       0 & 0 & 4 & 0 & 0 \\
       0 & 0 & 0 & 4 & 0 \\
       0 & 0 & 0 & 0 & 4
     \end{bmatrix}$

#### Задание 5.2

$\begin{bmatrix}
       1 & 2 & 3 \\
       4 & 0 & 6 \\
       7 & 8 & 9  
     \end{bmatrix}$

Определитель матрицы = $ 1*0*9 + 7*2*6 + 8*4*3 - 7*0*3 - 1*6*8 - 4*2*9 = 84 + 96 - 48 - 72 = 60$

In [2]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [3]:
D = np.linalg.det(A)
D

59.999999999999986

#### Задание 5.3 Вычислить матрицу, обратную данной:

$\begin{bmatrix}
       1 & 2 & 3 \\
       4 & 0 & 6 \\
       7 & 8 & 9  
     \end{bmatrix}$

In [4]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [5]:
B = np.linalg.inv(A)
B

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

#### Задание 5.4 Вычислить скалярное произведение двух векторов

$\left(1,5\right) * \left(2,8\right)$

In [6]:
A = np.array([1,5])
B = np.array([2,8])

In [7]:
P = np.dot(A,B)
P

42

#### Задание 5.5 Вычислить смешанное произведение трех векторов

In [8]:
A = np.array([1,5,0])
B = np.array([2,8,7])
C = np.array([7,1.5,3])
A, B, C

(array([1, 5, 0]), array([2, 8, 7]), array([7. , 1.5, 3. ]))

Смещанное произведение A*B*C = скалярное произведение A на векторное произведение [B x C]

In [9]:
ABC = np.dot(A, np.cross(B, C))
ABC

228.5